import type { Zutat } from "./types";

/* Feste Auswahllisten für Formulare, Filter und Kategorisierung */
export const ZUTAT_KATEGORIEN = ["Gemüse", "Obst", "Fleisch & Geflügel", "Fisch", "Molkereiprodukte", "Eier & Frischware", "Trockenware", "Konserven", "Hülsenfrüchte", "Gewürze & Saucen", "Sonstiges"];
/** EU-14-Liste der kennzeichnungspflichtigen Allergene. */
export const ALLERGENE_LISTE = ["Gluten", "Krebstiere", "Eier", "Fisch", "Erdnüsse", "Soja", "Milch", "Schalenfrüchte", "Sellerie", "Senf", "Sesam", "Sulfite", "Lupinen", "Weichtiere"];
export const ZUSATZSTOFFE_LISTE = ["Farbstoff", "Konservierungsstoff", "Antioxidationsmittel", "Geschmacksverstärker", "geschwefelt", "geschwärzt", "Phosphat", "Süßungsmittel", "enthält eine Phenylalaninquelle"];

export const zutaten: Zutat[] = [
  { id: "z-001", name: "Kartoffeln, festkochend", artikelnummer: "ART-0101", kategorie: "Gemüse", basiseinheit: "kg", einkaufseinheit: "Sack (25 kg)", umrechnungsfaktor: 25, einkaufspreis: 21.5, lieferant: "Rheinland Frische GmbH", allergene: [], zusatzstoffe: [], vegetarisch: true, vegan: true, bio: false, regional: true, aktiv: true, naehrwertePro100: { kcal: 77, eiweissG: 2.0, fettG: 0.1, kohlenhydrateG: 15.6, zuckerG: 0.8, salzG: 0.01, quelle: "Open Food Facts" } },
  { id: "z-002", name: "Hähnchenbrustfilet", artikelnummer: "ART-0202", kategorie: "Fleisch & Geflügel", basiseinheit: "kg", einkaufseinheit: "Karton (10 kg)", umrechnungsfaktor: 10, einkaufspreis: 68.9, lieferant: "Geflügelhof Brandt", allergene: [], zusatzstoffe: [], vegetarisch: false, vegan: false, bio: false, regional: true, aktiv: true, naehrwertePro100: { kcal: 110, eiweissG: 23.0, fettG: 1.5, kohlenhydrateG: 0, zuckerG: 0, salzG: 0.1, quelle: "USDA FoodData Central" } },
  { id: "z-003", name: "Vollmilch 3,5 %", artikelnummer: "ART-0303", kategorie: "Molkereiprodukte", basiseinheit: "l", einkaufseinheit: "Kiste (12 l)", umrechnungsfaktor: 12, einkaufspreis: 13.1, lieferant: "Molkerei Niederrhein", allergene: ["Milch"], zusatzstoffe: [], vegetarisch: true, vegan: false, bio: false, regional: true, aktiv: true, naehrwertePro100: { kcal: 64, eiweissG: 3.3, fettG: 3.5, kohlenhydrateG: 4.8, zuckerG: 4.8, salzG: 0.13, quelle: "Open Food Facts" } },
  { id: "z-004", name: "Weizenmehl Type 405", artikelnummer: "ART-0404", kategorie: "Trockenware", basiseinheit: "kg", einkaufseinheit: "Sack (10 kg)", umrechnungsfaktor: 10, einkaufspreis: 8.4, lieferant: "Mühle Reckmann", allergene: ["Gluten"], zusatzstoffe: [], vegetarisch: true, vegan: true, bio: false, regional: false, aktiv: true, naehrwertePro100: { kcal: 348, eiweissG: 10.0, fettG: 1.0, kohlenhydrateG: 72.0, zuckerG: 0.7, salzG: 0.01, quelle: "Open Food Facts" } },
  { id: "z-005", name: "Tomaten, passiert", artikelnummer: "ART-0505", kategorie: "Konserven", basiseinheit: "l", einkaufseinheit: "Karton (6 × 1 l)", umrechnungsfaktor: 6, einkaufspreis: 9.9, lieferant: "Bella Cucina Import", allergene: [], zusatzstoffe: [], vegetarisch: true, vegan: true, bio: false, regional: false, aktiv: true, naehrwertePro100: { kcal: 32, eiweissG: 1.4, fettG: 0.3, kohlenhydrateG: 5.3, zuckerG: 4.3, salzG: 0.35, quelle: "Open Food Facts" } },
  { id: "z-006", name: "Penne (Hartweizen)", artikelnummer: "ART-0606", kategorie: "Trockenware", basiseinheit: "kg", einkaufseinheit: "Karton (12 kg)", umrechnungsfaktor: 12, einkaufspreis: 17.8, lieferant: "Bella Cucina Import", allergene: ["Gluten"], zusatzstoffe: [], vegetarisch: true, vegan: true, bio: false, regional: false, aktiv: true, naehrwertePro100: { kcal: 359, eiweissG: 12.5, fettG: 1.8, kohlenhydrateG: 71.0, zuckerG: 3.2, salzG: 0.01, quelle: "Open Food Facts" } },
  { id: "z-007", name: "Rote Linsen", artikelnummer: "ART-0707", kategorie: "Hülsenfrüchte", basiseinheit: "kg", einkaufseinheit: "Sack (5 kg)", umrechnungsfaktor: 5, einkaufspreis: 12.2, lieferant: "BioGroß Handel", allergene: [], zusatzstoffe: [], vegetarisch: true, vegan: true, bio: true, regional: false, aktiv: true, naehrwertePro100: { kcal: 343, eiweissG: 24.0, fettG: 1.9, kohlenhydrateG: 56.0, zuckerG: 1.9, salzG: 0.02, quelle: "USDA FoodData Central" } },
  { id: "z-008", name: "Sahne 30 %", artikelnummer: "ART-0808", kategorie: "Molkereiprodukte", basiseinheit: "l", einkaufseinheit: "Kiste (10 l)", umrechnungsfaktor: 10, einkaufspreis: 24.5, lieferant: "Molkerei Niederrhein", allergene: ["Milch"], zusatzstoffe: [], vegetarisch: true, vegan: false, bio: false, regional: true, aktiv: false, naehrwertePro100: { kcal: 288, eiweissG: 2.4, fettG: 30.0, kohlenhydrateG: 3.2, zuckerG: 3.2, salzG: 0.08, quelle: "Open Food Facts" } },
  { id: "z-009", name: "Karotten", artikelnummer: "ART-0909", kategorie: "Gemüse", basiseinheit: "kg", einkaufseinheit: "Sack (10 kg)", umrechnungsfaktor: 10, einkaufspreis: 9.8, lieferant: "Rheinland Frische GmbH", allergene: [], zusatzstoffe: [], vegetarisch: true, vegan: true, bio: true, regional: true, aktiv: true, naehrwertePro100: { kcal: 41, eiweissG: 0.9, fettG: 0.2, kohlenhydrateG: 9.6, zuckerG: 4.7, salzG: 0.06, quelle: "Open Food Facts" } },
  { id: "z-010", name: "Zwiebeln", artikelnummer: "ART-1010", kategorie: "Gemüse", basiseinheit: "kg", einkaufseinheit: "Sack (10 kg)", umrechnungsfaktor: 10, einkaufspreis: 7.5, lieferant: "Rheinland Frische GmbH", allergene: [], zusatzstoffe: [], vegetarisch: true, vegan: true, bio: false, regional: true, aktiv: true, naehrwertePro100: { kcal: 40, eiweissG: 1.1, fettG: 0.1, kohlenhydrateG: 9.3, zuckerG: 4.2, salzG: 0.0, quelle: "Open Food Facts" } },
  { id: "z-011", name: "Rinderhack", artikelnummer: "ART-1111", kategorie: "Fleisch & Geflügel", basiseinheit: "kg", einkaufseinheit: "Karton (10 kg)", umrechnungsfaktor: 10, einkaufspreis: 74.0, lieferant: "Geflügelhof Brandt", allergene: [], zusatzstoffe: [], vegetarisch: false, vegan: false, bio: false, regional: true, aktiv: true, naehrwertePro100: { kcal: 176, eiweissG: 20.0, fettG: 10.0, kohlenhydrateG: 0, zuckerG: 0, salzG: 0.15, quelle: "USDA FoodData Central" } },
  { id: "z-012", name: "Lachsfilet, tiefgekühlt", artikelnummer: "ART-1212", kategorie: "Fisch", basiseinheit: "kg", einkaufseinheit: "Karton (5 kg)", umrechnungsfaktor: 5, einkaufspreis: 89.0, lieferant: "Nordsee Fischkontor", allergene: ["Fisch"], zusatzstoffe: [], vegetarisch: false, vegan: false, bio: false, regional: false, aktiv: true, naehrwertePro100: { kcal: 208, eiweissG: 20.4, fettG: 13.4, kohlenhydrateG: 0, zuckerG: 0, salzG: 0.08, quelle: "USDA FoodData Central" } },
  { id: "z-013", name: "Naturjoghurt", artikelnummer: "ART-1313", kategorie: "Molkereiprodukte", basiseinheit: "kg", einkaufseinheit: "Kübel (5 kg)", umrechnungsfaktor: 5, einkaufspreis: 9.9, lieferant: "Molkerei Niederrhein", allergene: ["Milch"], zusatzstoffe: [], vegetarisch: true, vegan: false, bio: true, regional: true, aktiv: true, naehrwertePro100: { kcal: 61, eiweissG: 3.5, fettG: 3.0, kohlenhydrateG: 4.7, zuckerG: 4.7, salzG: 0.1, quelle: "Open Food Facts" } },
  { id: "z-014", name: "Eier, Freiland (Kl. M)", artikelnummer: "ART-1414", kategorie: "Eier & Frischware", basiseinheit: "Stück", einkaufseinheit: "Palette (360 Stück)", umrechnungsfaktor: 360, einkaufspreis: 108.0, lieferant: "Geflügelhof Brandt", allergene: ["Eier"], zusatzstoffe: [], vegetarisch: true, vegan: false, bio: false, regional: true, aktiv: true, naehrwertePro100: { kcal: 143, eiweissG: 12.6, fettG: 9.9, kohlenhydrateG: 0.7, zuckerG: 0.4, salzG: 0.37, quelle: "USDA FoodData Central" } },
  { id: "z-015", name: "Reis, Basmati", artikelnummer: "ART-1515", kategorie: "Trockenware", basiseinheit: "kg", einkaufseinheit: "Sack (10 kg)", umrechnungsfaktor: 10, einkaufspreis: 19.5, lieferant: "Bella Cucina Import", allergene: [], zusatzstoffe: [], vegetarisch: true, vegan: true, bio: false, regional: false, aktiv: true, naehrwertePro100: { kcal: 349, eiweissG: 7.1, fettG: 0.7, kohlenhydrateG: 77.6, zuckerG: 0.1, salzG: 0.0, quelle: "USDA FoodData Central" } },
  { id: "z-016", name: "Kichererbsen", artikelnummer: "ART-1616", kategorie: "Hülsenfrüchte", basiseinheit: "kg", einkaufseinheit: "Sack (5 kg)", umrechnungsfaktor: 5, einkaufspreis: 13.9, lieferant: "BioGroß Handel", allergene: [], zusatzstoffe: [], vegetarisch: true, vegan: true, bio: true, regional: false, aktiv: true, naehrwertePro100: { kcal: 364, eiweissG: 19.3, fettG: 6.0, kohlenhydrateG: 61.0, zuckerG: 10.7, salzG: 0.02, quelle: "USDA FoodData Central" } },
  { id: "z-017", name: "Äpfel, Elstar", artikelnummer: "ART-1717", kategorie: "Obst", basiseinheit: "kg", einkaufseinheit: "Kiste (12 kg)", umrechnungsfaktor: 12, einkaufspreis: 15.6, lieferant: "Rheinland Frische GmbH", allergene: [], zusatzstoffe: [], vegetarisch: true, vegan: true, bio: true, regional: true, aktiv: true, naehrwertePro100: { kcal: 52, eiweissG: 0.3, fettG: 0.2, kohlenhydrateG: 13.8, zuckerG: 10.4, salzG: 0.0, quelle: "Open Food Facts" } },
  { id: "z-018", name: "Bananen", artikelnummer: "ART-1818", kategorie: "Obst", basiseinheit: "kg", einkaufseinheit: "Kiste (18 kg)", umrechnungsfaktor: 18, einkaufspreis: 21.6, lieferant: "Bella Cucina Import", allergene: [], zusatzstoffe: [], vegetarisch: true, vegan: true, bio: false, regional: false, aktiv: true, naehrwertePro100: { kcal: 89, eiweissG: 1.1, fettG: 0.3, kohlenhydrateG: 22.8, zuckerG: 12.2, salzG: 0.0, quelle: "USDA FoodData Central" } },
  { id: "z-019", name: "Butter", artikelnummer: "ART-1919", kategorie: "Molkereiprodukte", basiseinheit: "kg", einkaufseinheit: "Karton (10 kg)", umrechnungsfaktor: 10, einkaufspreis: 68.0, lieferant: "Molkerei Niederrhein", allergene: ["Milch"], zusatzstoffe: [], vegetarisch: true, vegan: false, bio: false, regional: true, aktiv: true, naehrwertePro100: { kcal: 717, eiweissG: 0.9, fettG: 81.0, kohlenhydrateG: 0.1, zuckerG: 0.1, salzG: 0.02, quelle: "Open Food Facts" } },
  { id: "z-020", name: "Sojasauce", artikelnummer: "ART-2020", kategorie: "Gewürze & Saucen", basiseinheit: "l", einkaufseinheit: "Kanister (5 l)", umrechnungsfaktor: 5, einkaufspreis: 22.5, lieferant: "Bella Cucina Import", allergene: ["Soja", "Gluten"], zusatzstoffe: ["Konservierungsstoff"], vegetarisch: true, vegan: true, bio: false, regional: false, aktiv: true, naehrwertePro100: { kcal: 60, eiweissG: 6.0, fettG: 0.1, kohlenhydrateG: 8.0, zuckerG: 0.8, salzG: 14.0, quelle: "Manuell" } },
];

export const zutatById = (id: string) => zutaten.find((z) => z.id === id);
